LineLength:
  Enabled: true
  Max: 128

Encoding:
  Enabled: false

# The rubocop Documentation cop is a duplicate of the Reek IrresponsibleModule
# check.
Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false

# MethodLength is superseded by Reek's TooManyStatements smell-finder.
MethodLength:
  Enabled: false
